/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Teliri (https://sketchfab.com/Teliri)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/coronavirus-b28f63adc5f04a2aab27e1d7293eba0b
title: Coronavirus
*/

import React, { useRef } from "react";
import { useGLTF, Html } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Corona(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/corona.glb");
  useFrame((state, delta) => {
    group.current.rotation.y += 0.004;
  })
  return (
    <group ref={group} {...props} dispose={null} scale={0.02}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/**First Section */}
        <Html>
          <div
            style={{
              top:"-150px",
              left:"-50vw",
              width:"100vw",
              textAlign:"center",
              position:"absolute",
            }}
          >
            <h2>Hello, I'm COVID-19</h2>
          </div>
          <div
            style={{
              top:"100px",
              left:"-50vw",
              width:"100vw",
              textAlign:"center",
              position:"absolute",
            }}
          >
            <h2>Let me tell you my story</h2>
          </div>
        </Html>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.SphereLow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/corona.glb");