/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: YouniqueĪdeaStudio (https://sketchfab.com/sinnervoncrawsz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/flag-in-the-wind-563b39480a6745d599eff1c90a38b47f
title: flag in the wind
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Flag(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/flag.glb");
  return (
    <group ref={group} {...props} dispose={null} scale={2} position={[17,-2,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[0, 0.6, 1.54]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.4, 0.6, 1]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.steag_0.geometry}
            material={nodes.steag_0.material}
          />
        </group>
        <group position={[0, -0.01, 0.98]} scale={[0.02, 0.02, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.stick_0.geometry}
            material={nodes.stick_0.material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/flag.glb");
