/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cig3d (https://sketchfab.com/cig3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/statistic-charts-with-arrow-86f9238bdaf44e098b6da4d82ee1861f
title: Statistic Charts With Arrow
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Stonks(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/stonks.glb");
  return (
    <group ref={group} {...props} dispose={null} position={[23,-1,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.25, 0, 0]} scale={[0.32, 0.32, 0.28]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_0.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group position={[0.61, 0, 0]} scale={[0.32, 0.32, 0.53]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001_0.geometry}
            material={materials["Material.003"]}
          />
        </group>
        <group position={[1.44, 0, 0]} scale={[0.32, 0.32, 0.78]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube002_0.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          position={[-1.48, -0.05, 0.21]}
          rotation={[0, 0.57, 0]}
          scale={[0.09, 0.07, 0.58]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_0.geometry}
            material={materials["Material.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/stonks.glb");
