/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: VRC-IW (https://sketchfab.com/VRC-IW)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/az-vaccine-vial-a1bb302ae09645e78cbda7bd53fd9dff
title: AZ Vaccine vial
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Vaccine(props) {
  const group = useRef();
  useFrame(() => {
    group.current.rotation.y += 0.01;
  })
  const { nodes, materials } = useGLTF("/vaccine.glb");
  return (
    <group ref={group} {...props} dispose={null}
        scale={0.4}
        position={[56,0,0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_Glass_0.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_aluminium_0.geometry}
              material={materials.aluminium}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_Label_0.geometry}
              material={materials.Label}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/vaccine.glb");
