/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Austin Beaulier (https://sketchfab.com/Austin.Beaulier)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/checkmark-6605c7cc1da849e9bf50b3c8e408aa73
title: Checkmark
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Checkmark(props) {
  const group = useRef();
  useFrame(({clock}) => {
    group.current.rotation.y = Math.sin(clock.getElapsedTime()) * 0.2;
  })
  const { nodes, materials } = useGLTF("/checkmark.glb");
  return (
    <group ref={group} {...props} dispose={null} scale={0.3} position={[-3,-1,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/checkmark.glb");
