/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Rifeor (https://sketchfab.com/Rifeor)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/road-sign-exclamation-point-a7af74051d4c4934b1615f5008e2e521
title: Road sign exclamation Point
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Exclamationmark(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/exclamationmark.glb");
  useFrame(({clock}) => {
   
  })
  return (
    <group ref={group} {...props} dispose={null} scale={0.01} 
      position={[2,-15,0]}
      rotation={[0,65.5,0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Material003_0.geometry}
              material={materials["Material.003"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/exclamationmark.glb");
