/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: zeroran (https://sketchfab.com/zeroran)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/anatomy-study-20-basemesh-human-male-body-c3f13a4baa2f4ea5a0a88d29e7fa1779
title: Anatomy study 2.0 Basemesh Human Male Body
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Humanbody(props) {
  const { nodes, materials } = useGLTF("/humanbody.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Scene_-_Root"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["Scene_-_Root"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials["Scene_-_Root"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/humanbody.glb");