/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: titopetri (https://sketchfab.com/titopetri)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/8a-serie-biologia-corona-virus-covid-19-6bd08779f1b045faab1d93304b869355
title: 8ª série - BIOLOGIA - Corona Vírus COVID-19
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CovidInside(props) {
  const { nodes, materials } = useGLTF("/covidinside.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0.16, -0.18, 0.32]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["Material.005"]}
          />
          <group rotation={[-0.06, 0.09, -1.57]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials["Material.004"]}
            />
          </group>
          <group rotation={[0.88, -0.18, -2.49]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials["Material.003"]}
            />
          </group>
          <group
            position={[0.07, 0.09, 0.21]}
            rotation={[-2.3, -0.63, 2.95]}
            scale={0.34}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group rotation={[0, 0, -0.97]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <group rotation={[-1.14, 1.13, 2.5]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials["Material.003"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/covidinside.glb");
