/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sajith Rajan (https://sketchfab.com/sajithtrajan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/corona-virus-ead521a012e84b03ae0e3aab96f7f01d
title: Corona Virus
*/

import { useRef, useState } from "react";
import { useGLTF, Html } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function GammaCorona(props) {
  const [hovered, setHovered] = useState(false)
  const group = useRef();
  useFrame((state, delta) => {
    group.current.rotation.z += 0.01;
    group.current.rotation.x += 0.01;
  })
  const { nodes, materials } = useGLTF("/gamma.glb");
  return (
    <group ref={group} {...props} dispose={null} scale={38}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <Html scaleFactor={10}
        style={{
          pointerEvents: "none", 
          display: hovered ? "block" : "none",
          color:"white",
          padding:"10px",
          backgroundColor:"rgba(0,0,0,0.5)",
          borderRadius:"5px",
        }}
      >
        <div className="content">
          Amusement purposes only
        </div>
      </Html>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Group11311_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/gamma.glb");
