/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Sajith Rajan (https://sketchfab.com/sajithtrajan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/corona-virus-ead521a012e84b03ae0e3aab96f7f01d
title: Corona Virus
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function GammaCorona(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/gamma.glb");
  return (
    <group ref={group} {...props} dispose={null} scale={38}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Group11311_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/gamma.glb");
